name: Build GH Pages Web app for testing

on:
  workflow_run:
     workflows: ["Analyze and Test"]
     types: [completed] #requested

permissions:
  id-token: write # For actions/deploy-pages
  contents: write # For committing to repo for GitHub Pages for actions/deploy-pages
  pages: write    # Required for actions/deploy-pages

jobs:
   on-success-build-and-publish-web:
     name: Build and Deploy Web App to GitHub Pages
     runs-on: ubuntu-latest
     # IMPORTANT: Runs only if the "Analyze and Test" workflow completed successfully
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
      - run: echo "Analyze and Test succeeded - deploy starting"

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.7'
          channel: 'stable'
          cache: true

      - name: Install dependencies  
        run: flutter pub get

      - name: Build Flutter web app
        run: flutter build web --release --base-href /medicines-for-children-flutter/

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          # Path to the directory containing the static assets to be deployed.
          # Flutter web builds to 'build/web' by default.
          path: './build/web'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


   on-failure:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'failure' }}
     steps:
       - run: echo "Analyze and Test failed - deploy aborted"
  
